#!/usr/bin/env bash
set -Eeuo pipefail

# ==============================================================================
# MasterBuilder - Prowlarr Quick Configuration
# ==============================================================================
# Configures:
#   - Sonarr application in Prowlarr
#   - Radarr application in Prowlarr
#   - TRAWL as a FlareSolverr-compatible proxy
#
# Safe to run multiple times:
# existing entries are detected and skipped.
#
# ==============================================================================

PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

info()  { printf '[+] %s\n' "$1"; }
warn()  { printf '[!] %s\n' "$1"; }
fatal() { printf '[X] %s\n' "$1" >&2; exit 1; }


# ------------------------------------------------------------------------------
# Load project environment
# ------------------------------------------------------------------------------

[[ -f "$ENV_FILE" ]] || fatal "Missing .env file."

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${CONFIG_ROOT:?CONFIG_ROOT is missing from .env}"

PROWLARR_PORT="${PROWLARR_PORT:-9696}"
SONARR_PORT="${SONARR_PORT:-8989}"
RADARR_PORT="${RADARR_PORT:-7878}"

PROWLARR_HOST_URL="http://localhost:${PROWLARR_PORT}"


# ------------------------------------------------------------------------------
# Read API keys generated by the applications
# ------------------------------------------------------------------------------

wait_for_config() {
    local name="$1"
    local file="$2"
    local waited=0

    info "Waiting for $name configuration..." >&2       

    until [[ -s "$file" ]]; do
        if (( waited >= 120 )); then
            fatal "$name config.xml did not appear: $file"
        fi

        sleep 2
        ((waited += 2))
    done
}


read_api_key() {
    local name="$1"
    local file="$2"
    local key

    wait_for_config "$name" "$file"

    key="$(
        sed -n \
            's:.*<ApiKey>\([^<]*\)</ApiKey>.*:\1:p' \
            "$file" \
        | head -n 1
    )"

    [[ -n "$key" ]] || fatal "Could not read $name API key."

    printf '%s' "$key"
}


PROWLARR_API_KEY="$(
    read_api_key \
        "Prowlarr" \
        "$CONFIG_ROOT/prowlarr/config.xml"
)"

SONARR_API_KEY="$(
    read_api_key \
        "Sonarr" \
        "$CONFIG_ROOT/sonarr/config.xml"
)"

RADARR_API_KEY="$(
    read_api_key \
        "Radarr" \
        "$CONFIG_ROOT/radarr/config.xml"
)"


# ------------------------------------------------------------------------------
# Wait for APIs
# ------------------------------------------------------------------------------

wait_for_api() {
    local name="$1"
    local url="$2"
    local api_key="$3"
    local waited=0

    info "Waiting for $name API..."

    until curl -fsS \
        -H "X-Api-Key: $api_key" \
        "$url" \
        >/dev/null 2>&1
    do
        if (( waited >= 120 )); then
            fatal "$name API did not become ready."
        fi

        sleep 2
        ((waited += 2))
    done

    info "$name API is ready."
}


wait_for_api \
    "Prowlarr" \
    "$PROWLARR_HOST_URL/api/v1/system/status" \
    "$PROWLARR_API_KEY"

wait_for_api \
    "Sonarr" \
    "http://localhost:${SONARR_PORT}/api/v3/system/status" \
    "$SONARR_API_KEY"

wait_for_api \
    "Radarr" \
    "http://localhost:${RADARR_PORT}/api/v3/system/status" \
    "$RADARR_API_KEY"


# ------------------------------------------------------------------------------
# Wait for TRAWL
# ------------------------------------------------------------------------------

info "Waiting for TRAWL..."

waited=0

until docker exec trawl \
    curl -fsS http://localhost:8191/health \
    >/dev/null 2>&1
do
    if (( waited >= 120 )); then
        fatal "TRAWL did not become ready."
    fi

    sleep 2
    ((waited += 2))
done

info "TRAWL is ready."


# ------------------------------------------------------------------------------
# Prowlarr API helpers
# ------------------------------------------------------------------------------

prowlarr_get() {
    local endpoint="$1"

    curl -fsS \
        -H "X-Api-Key: $PROWLARR_API_KEY" \
        "$PROWLARR_HOST_URL$endpoint"
}


# ------------------------------------------------------------------------------
# Prowlarr POST helpers
# ------------------------------------------------------------------------------

PROWLARR_LAST_HTTP_STATUS=""
PROWLARR_LAST_RESPONSE=""


prowlarr_post_capture() {
    local endpoint="$1"
    local payload="$2"

    local response_file

    response_file="$(mktemp)"

    PROWLARR_LAST_HTTP_STATUS="$(
        curl -sS \
            -o "$response_file" \
            -w '%{http_code}' \
            -X POST \
            -H "X-Api-Key: $PROWLARR_API_KEY" \
            -H "Content-Type: application/json" \
            --data "$payload" \
            "$PROWLARR_HOST_URL$endpoint" \
            || true
    )"

    PROWLARR_LAST_RESPONSE="$(
        cat "$response_file"
    )"

    rm -f "$response_file"
}


wait_for_application_exists() {
    local implementation="$1"
    local timeout="${2:-10}"

    local waited=0

    while (( waited < timeout )); do

        if application_exists "$implementation"; then
            return 0
        fi

        sleep 1
        ((waited += 1))
    done

    return 1
}


create_application_with_retry() {
    local implementation="$1"
    local display_name="$2"
    local payload="$3"

    local attempt
    local max_attempts=6

    if application_exists "$implementation"; then
        info "$display_name already exists in Prowlarr. Skipping."
        return
    fi


    for (( attempt=1; attempt<=max_attempts; attempt++ )); do

        info "Adding $display_name to Prowlarr..."

        prowlarr_post_capture \
            "/api/v1/applications" \
            "$payload"


        # ----------------------------------------------------------------------
        # Prowlarr may return an error while the application was still created.
        #
        # Give the application a few seconds to appear before deciding that the
        # POST genuinely failed.
        # ----------------------------------------------------------------------

        if wait_for_application_exists "$implementation" 10; then

            if [[ "$PROWLARR_LAST_HTTP_STATUS" =~ ^2[0-9][0-9]$ ]]; then
                info "$display_name added."
            else
                warn "$display_name was created despite HTTP $PROWLARR_LAST_HTTP_STATUS."
            fi

            return
        fi


        # ----------------------------------------------------------------------
        # Normal success response, but application still has not appeared.
        # Treat it as transient and retry.
        # ----------------------------------------------------------------------

        if [[ "$PROWLARR_LAST_HTTP_STATUS" =~ ^2[0-9][0-9]$ ]]; then

            warn "$display_name POST succeeded with HTTP $PROWLARR_LAST_HTTP_STATUS,"
            warn "but the application has not appeared yet."

        else

            warn "$display_name creation returned HTTP $PROWLARR_LAST_HTTP_STATUS."

            if [[ -n "$PROWLARR_LAST_RESPONSE" ]]; then
                warn "Prowlarr response:"

                printf '%s\n' "$PROWLARR_LAST_RESPONSE" |
                    head -c 1000 >&2

                printf '\n' >&2
            fi
        fi


        if (( attempt < max_attempts )); then

            warn "Retrying $display_name in 3 seconds..."
            sleep 3

        fi
    done


    # --------------------------------------------------------------------------
    # One final check before failing.
    # --------------------------------------------------------------------------

    if application_exists "$implementation"; then
        info "$display_name exists in Prowlarr."
        return
    fi


    fatal "Could not configure $display_name in Prowlarr after $max_attempts attempts."
}


application_exists() {
    local implementation="$1"

    prowlarr_get "/api/v1/applications" |
        grep -Eq \
        "\"implementation\"[[:space:]]*:[[:space:]]*\"${implementation}\""
}


proxy_exists() {
    local name="$1"

    prowlarr_get "/api/v1/indexerproxy" |
        grep -Eq \
        "\"name\"[[:space:]]*:[[:space:]]*\"${name}\""
}


# ------------------------------------------------------------------------------
# Sonarr
# ------------------------------------------------------------------------------

configure_sonarr() {

    if application_exists "Sonarr"; then
        info "Sonarr already exists in Prowlarr. Skipping."
        return
    fi

    info "Adding Sonarr to Prowlarr..."

    local payload

    payload="$(cat <<JSON
{
  "syncLevel": "fullSync",
  "enable": true,
  "name": "Sonarr",
  "fields": [
    {
      "name": "prowlarrUrl",
      "value": "http://prowlarr:9696"
    },
    {
      "name": "baseUrl",
      "value": "http://sonarr:8989"
    },
    {
      "name": "apiKey",
      "value": "$SONARR_API_KEY"
    },
    {
      "name": "authUsername",
      "value": ""
    },
    {
      "name": "authPassword",
      "value": ""
    },
    {
      "name": "syncCategories",
      "value": [
        5000,
        5010,
        5020,
        5030,
        5040,
        5045,
        5050,
        5090
      ]
    },
    {
      "name": "animeSyncCategories",
      "value": [
        5070
      ]
    },
    {
      "name": "syncAnimeStandardFormatSearch",
      "value": true
    },
    {
      "name": "syncRejectBlocklistedTorrentHashesWhileGrabbing",
      "value": false
    }
  ],
  "implementationName": "Sonarr",
  "implementation": "Sonarr",
  "configContract": "SonarrSettings",
  "tags": []
}
JSON
)"

    create_application_with_retry \
        "Sonarr" \
        "Sonarr" \
        "$payload"
}


# ------------------------------------------------------------------------------
# Radarr
# ------------------------------------------------------------------------------

configure_radarr() {

    if application_exists "Radarr"; then
        info "Radarr already exists in Prowlarr. Skipping."
        return
    fi

    info "Adding Radarr to Prowlarr..."

    local payload

    payload="$(cat <<JSON
{
  "syncLevel": "fullSync",
  "enable": true,
  "name": "Radarr",
  "fields": [
    {
      "name": "prowlarrUrl",
      "value": "http://prowlarr:9696"
    },
    {
      "name": "baseUrl",
      "value": "http://radarr:7878"
    },
    {
      "name": "apiKey",
      "value": "$RADARR_API_KEY"
    },
    {
      "name": "authUsername",
      "value": ""
    },
    {
      "name": "authPassword",
      "value": ""
    },
    {
      "name": "syncCategories",
      "value": [
        2000,
        2010,
        2020,
        2030,
        2040,
        2045,
        2050,
        2060,
        2070,
        2080,
        2090
      ]
    },
    {
      "name": "syncRejectBlocklistedTorrentHashesWhileGrabbing",
      "value": false
    }
  ],
  "implementationName": "Radarr",
  "implementation": "Radarr",
  "configContract": "RadarrSettings",
  "tags": []
}
JSON
)"

    create_application_with_retry \
        "Radarr" \
        "Radarr" \
        "$payload"
}


# ------------------------------------------------------------------------------
# TRAWL
# ------------------------------------------------------------------------------

configure_trawl() {

    if proxy_exists "TRAWL"; then
        info "TRAWL already exists in Prowlarr. Skipping."
        return
    fi

    info "Adding TRAWL proxy to Prowlarr..."

    local payload

    payload="$(cat <<'JSON'
{
  "onHealthIssue": false,
  "supportsOnHealthIssue": false,
  "includeHealthWarnings": false,
  "name": "TRAWL",
  "fields": [
    {
      "name": "host",
      "value": "http://trawl:8191/"
    },
    {
      "name": "requestTimeout",
      "value": 60
    }
  ],
  "implementationName": "FlareSolverr",
  "implementation": "FlareSolverr",
  "configContract": "FlareSolverrSettings",
  "tags": []
}
JSON
)"

    prowlarr_post_capture "/api/v1/indexerproxy" "$payload"

    info "TRAWL proxy added."
}


# ------------------------------------------------------------------------------
# Run configuration
# ------------------------------------------------------------------------------

printf '\n'
printf '============================================================\n'
printf 'PROWLARR QUICK CONFIGURATION\n'
printf '============================================================\n'

configure_sonarr
configure_radarr
configure_trawl

# INDEXERS creator
INDEXER_BOOTSTRAP="$PROJECT_ROOT/bootstrap/prowlarr/indexers.sh"

[[ -f "$INDEXER_BOOTSTRAP" ]] ||
    fatal "Missing Prowlarr indexer bootstrap: $INDEXER_BOOTSTRAP"

# shellcheck disable=SC1090
source "$INDEXER_BOOTSTRAP"

configure_public_indexers
configure_private_indexers

printf '\n'
printf '============================================================\n'
printf 'PROWLARR CONFIGURATION COMPLETE\n'
printf '============================================================\n'

info "Sonarr: configured"
info "Radarr: configured"
info "TRAWL:  configured"
